version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - .env
    volumes:
      - .:/back
      - /back/node_modules
    command: pnpm start:prod